### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by lubien** [TABmk/2FA-HOTP-TOTP#1]
Tested on my local machine and also tested on repl.it

https://repl.it/@lubien/RotatingPersonalCoderesource#index.js

```sh
HOTP code generate test: 941117
HOTP code validator test (current code passed, null = fail): -1
HOTP code validator test (fake code passed, null = fail): null
TOTP code generate test: 473221
TOTP code validator test (current code passed, null = fail): -1
TOTP code validator test (fake code passed, null = fail): null
base32 converter (no padding) ORSXG5A
```

**Comment by TABmk** [comment]
@lubien Hi, thank you for reporting this bug! I somehow messed up window delta calculating in HOTP verification. Just fixed it (https://github.com/TABmk/2FA-HOTP-TOTP/commit/4059a3e54823ec4bc04856341f9afabcc298616e) and updated npm package to 1.0.6. Just tested, now both validators returns 0. And TOTP 30 sec old code returns -1 with 1 window (which is -1, 0 ,1)

repl.it with 1.0.6 https://repl.it/@TABmk/RotatingPersonalCoderesource-1

**Comment by lubien** [comment]
Awesome!
