### ISSUE TITLE
Update documentation to require NodeJS v15 or later for generateKey function

### ISSUE THREAD

**Issue by arthur-clq** [TABmk/2fa-hotp-totp#3]
Hi,

Thank you for creating this amazing library. I have a suggestion to indicate that Nodejs v15 or later is required to run `generateKey` because `generateKeySync` is only available on v15 or later.

I hope this would help others because I spent 10 minutes figuring out why its not working until I read through the Nodejs crypto docs.

**Comment by TABmk** [comment]
Hi, @arthur-clq 

Thanks for letting me know about missing info
Just updated readme, docs and npm
[v2.1.2 patch](https://www.npmjs.com/package/2fa-hotp-totp) is on npm already
